name: workspace
description: Library that allow multiple panels rearrange to each other.
version: 0.1.0
homepage: https://github.com/VladimirCores/Flutter-Flex-Layout-Workspace

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true
